const ignore = [
  "Dmitry / Sergei",
  "Welcome Call",
  "Ilya<>Sergey",
  "Welcome Sergey",
  "Sergey / Dmitry",
  "pre-commits",
  "Spinner + estimated time remaining",
  "Loading animation UI bugs",
  "Colors",
  "Sergei / Aleksei - say hi",
  "Sergei / Brendan intro",
  "Logs statuses",
  "Sergei x Roza",
  "Widget Release",
  "Sergei / Artem",
  "Sergey / Danial",
  "Sergei Nekrasov's Zoom Meeting",
  "Typography",
  "Encompass",
  "Percy",
  "Close the sprint",
  "Reminder: Update OKRs",
  "Relocation sync",
  "Sergei / Roza",
  "Deel / Truv - User Demo / Q&A",
  "Storypoints vs time",
  "Zaynah Marani (Marani Law LLP) - Sergei Nekrasov (Citadel)",
  "Product review invite to present widget v3",
  "Redesign a/b steps",
];

const aliases = {
  ...ignore.reduce((acc, title) => {
    acc[title] = null;

    return acc;
  }, {}),
  "Sergey Nekrasov | Aleksei Veselovskii (Frontend Engineer)":
    "On-site Interviews",
  "Lidia Zhabo (Frontend Engineer)": "On-site Interviews",
  "On-site - Viсtoria Kuchina - Senior Fullstack Engineer - Client":
    "On-site Interviews",
  "On-site - Dmitry Kiyatkin - Senior Fullstack Engineer - Client":
    "On-site Interviews",
  "On-site - Gustavo Lima - Senior Software Engineer - Integrations, Crawler":
    "On-site Interviews",
  "Gustavo Debrief (Front End Engineer)": "On-site Interviews",
  "Deep dive interview - Adeel Asif": "On-site Interviews",
  "Weekly Show & Tell": "Show & Tell",
  "Review widget UI": "UI review",
  "Design review": "UI review",
  "Doc upload: design review": "UI review",
  "UX daily standup": "Stand up",
  "Consumer team daily standup": "Stand up",
  "Clients team standup": "Stand up",
  "Clients team status sync": "Stand up",
  "UX Team retro": "Retro",
  "Sprint retro": "Retro",
  "Next Sprints tasks estimation and decomposition": "Sprint planning",
  "Eng Planning: UX": "Sprint planning",
  "Next Sprint AMA": "Sprint planning",
  "Eng Planning: Client team": "Sprint planning",
  "Eng Planning: Consumer team": "Sprint planning",
  "Eng Seminar": "All engineers",
  "Engineering All Hands": "All engineers",
  "A/B test sync": "Analytics deep dive",
  "A/B test discrepancies": "Analytics deep dive",
  "Metabase workshop": "Analytics deep dive",
  "AB testing flow": "Analytics deep dive",
  "User identification in AB test": "Analytics deep dive",
  "Internal Backlog Grooming": "Grooming",
  "Encompass Frontend Kick start": "Grooming",
  "Json-forms / Custom fields to the provider login screen": "Grooming",
  "Time to discuss tasks": "Grooming",
  "Custom forms on Login screen sync": "Grooming",
  "Widget reload meeting": "Grooming",
  "Task Grooming": "Grooming",
  "Custom forms sync": "Grooming",
  "Embed reset flow in Citadel widget": "Grooming",
  "Design grooming: showing error on the login page": "Grooming",
  "Consumer FE+BE grooming": "Grooming",
  "Custom Forms Rethink": "Grooming",
  "Custom forms": "Grooming",
  "TWN vs Docs Upload": "Grooming",
  "SDK discussion": "Grooming",
  "Can we make custom forms in reset flow?": "Grooming",
  "New designs grooming": "Grooming",
  "Custom forms Help links": "Grooming",
  "Review full story": "Fullstory review",
};

module.exports = aliases;
